### ISSUE TITLE
Transpec ignoring --keep option

### ISSUE THREAD

**Issue by jeremywadsack** [yujinakayama/transpec#103]
We use `mocha` for mocks so I don't want `transpec` changing my `stub` calls. I used the following command (from the README) to have it ignore conversions for mocking:

    transpec --keep should_receive,stub

However, I get the following as part of the response:

```
37 conversions
  from: stub('something')
    to: double('something')
```

Am I missing something?

Environment:
- Transpec version 3.1.0
- ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin14.0]

**Comment by yujinakayama** [comment]
I couldn't reproduce it. Here's a example project:

* https://gist.github.com/yujinakayama/8e79c301c6006fd70943

Also, you don't need to use `--keep` option because Transpec automatically differentiate RSpec's `stub` and Mocha's `stub`.

**Comment by jeremywadsack** [comment]
It could be because we are running this on a Rails 4 project that includes Minitest

**Comment by jeremywadsack** [comment]
Sorry hit the wrong button there. 

I am going to continue investigating this and see if I can figure out what's causing the problem. I can add the `p method(:stub)` call to one of the lines and see if that shows anything.

**Comment by jeffutter** [comment]
I'm having the same issue on an older project using RR mocks and stubs. It changes them to double which isn't a valid thing even with -k stub

**Comment by yujinakayama** [comment]
Could you provide a reproducible example? I cannot reproduce it in my environment.

**Comment by jeremywadsack** [comment]
In subsequent uses I have not run into this error again. For my part you can close this issue and I can't reproduce it anymore.

**Comment by jeffutter** [comment]
I have figured out what my problem was. I am working on a project that uses ```rr``` for it's mock/stub library. If I run transpec It converts all of my mock/stub method calls to double which ```rr``` does not recognize. I would expect that ``` -k stub ``` would not convert these. However it still does. ``` -k deprecated ``` on the other hand keeps them. I'm not sure if this is intended or not? If it is, perhaps the docs need some clarification.

**Comment by yujinakayama** [comment]
`-k stub` is for RSpec's `obj.stub(:message)` syntax.

* https://github.com/yujinakayama/transpec#conversions-enabled-by-default

Transpec discriminates RSpec's methods from other libraries' methods even they have same name, and converts only RSpec's ones.
