### ISSUE TITLE
Failed conversion of should have(:no)

### ISSUE THREAD

**Issue by nevans** [yujinakayama/transpec#107]
````diff
- subject.should have(:no).foos
+ expect(subject.foos.size).to eq(:no)
````

The correct conversion would have been `eq(0)`

* transpec 3.1.0
* rspec 2.99.0
* ruby 2.0.0-p645
* no command line arguments passed to transpec

**Comment by yujinakayama** [comment]
Thanks for the report. It's fixed in Transpec 3.1.1.
