### ISSUE TITLE
transpec hanging when converting certain spec

### ISSUE THREAD

**Issue by mattfik** [yujinakayama/transpec#108]
When running transpec (with no options) everything runs fine until the file conversion begins. Several files convert successfully, but when I get to a certain file (link below) it hangs. Running transpec on only the troublesome file (again with no options) still hangs. I removed the file, ran transpec for all specs again, and everything complete successfully, no problems. I'm totally lost as to what could be causing this. 

**Transpec version** `3.1.1`
**Ruby version** `1.9.3p448 (2013-06-27 revision 41675) [x86_64-darwin14.1.0]`
**RSpec version** `2.99.2`

Here's a link to the problematic file https://gist.github.com/mattfik/d529f9b5b1062b151025

Let me know if any more info is required.

Thanks!

**Comment by yujinakayama** [comment]
It was caused by [this line](https://gist.github.com/mattfik/d529f9b5b1062b151025#file-order_from_spec-rb-L157). Was the example passing?
