### ISSUE TITLE
Out of space when copying project for dynamic analysis

### ISSUE THREAD

**Issue by hahcho** [yujinakayama/transpec#110]
One of the project I am working is quite big(11G). The problem arises from the fact that my `/tmp` is only 2GB because it uses `tmpfs` so the project cannot be copied there(it results in some IO exception saying I am out of space). I fixed the issue by passing an argument to `Dir#mktmpdir` in [dynamic_analyzer.rb](https://github.com/yujinakayama/transpec/blob/master/lib/transpec/dynamic_analyzer.rb#L56) as the target directory where the project should be copied.

Do you think making a special argument passed to the `transpec` command giving the directory where the project should be copied is a good idea?

I think this can be a common issue because a lot of people use `tmpfs` which is bound to the ram size, which some times is not enough for copying a whole project.

**Comment by yujinakayama** [comment]
You can change the temporary directory in Transpec by specifying `TMPDIR` environment variable as `TMPDIR=/path/to/dir transpec`, since the `Dir.mktmpdir` refers it:

* https://github.com/ruby/ruby/blob/v2_2_3/lib/tmpdir.rb#L25

**Comment by hahcho** [comment]
Thanks, haven't seen it. No need for custom features. Maybe update the
README?
