### ISSUE TITLE
Transpec didn't update `type: :route` to `type: :routing`

### ISSUE THREAD

**Issue by dgmstuart** [yujinakayama/transpec#111]
Hi - I had some passing specs on 2.99 which were like:
```ruby
RSpec.describe "routing to verifications", type: :route do
```

...but in RSpec 3 the correct form is:
```ruby
RSpec.describe "routing to verifications", type: :routing do
```

Is Transpec expected to have updated this, or was `:route` never a thing anyway?

**Comment by dgmstuart** [comment]
(P.S. Thanks so much for transpec: it's magic!!)

**Comment by yujinakayama** [comment]
It's intentional. Transpec automatically adds `:type` metadata only when it's not yet speified. If you explicitly specified the wrong `:type` metadata, it's your responsibility.

**Comment by dgmstuart** [comment]
OK thanks for letting me know. 

As I understand it though `type: :route` isn't _wrong_ - just out of date.
