### ISSUE TITLE
transpec can't handle project that isn't git root

### ISSUE THREAD

**Issue by josephks** [yujinakayama/transpec#112]
I have a gem that lives in a subdirectory of a git repository.  When I try to run transpec I get:

```
$ transpec -f
Copying the project for dynamic analysis...
Running dynamic analysis with command "bundle exec rspec"...
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
The path `/private/var/folders/8d/lqz6jwkd3d5b9pkp9tx006gc0000gp/T/d20151214-1906-1wgx2sk/xzy123` does not exist.

Failed running dynamic analysis. Transpec runs your specs in a copied project directory. If your project requires some special setup or commands to run specs, use -c/--rspec-command option.

 $ transpec --version
3.1.1
 $ bundle exec rspec --version
3.1.3
 $ ruby --version
ruby 2.0.0p647 (2015-08-18 revision 51631) [x86_64-darwin14.5.0]

```

Using `--rspec-command "cd xyz123 ; bundle exec rspec" does not work.  It results in
```
Copying the project for dynamic analysis...
Running dynamic analysis with command "cd xyz123 ; bundle exec rspec"...
/Users/jshraibman/.rvm/gems/ruby-2.0.0-p647/gems/transpec-3.1.1/lib/transpec/spec_file_finder.rb:26:in `base_paths': Specify target files or directories. (ArgumentError)

```

**Comment by yujinakayama** [comment]
I could not reproduce the error in my environment. Can you provide a reproducible project?

**Comment by josephks** [comment]
I just tried and the problem I'm having seems to be different than what I though it was.  The "fatal: Not a git repository (or any of the parent directories): .git" error message has gone away but I'm still getting the directory missing error.  I'm working on a test case.

**Comment by josephks** [comment]
OK so this problem I'm having has nothing to do with the project root not being git root.  That was a red herring.

I have a git repo here: https://github.com/josephks/bug_demo

If you check that out and cd into the demo_app directory and run `spec` the specs run.  If you run `transpec` you get:
```
Copying the project for dynamic analysis...
Running dynamic analysis with command "bundle exec rspec"...
The path `/private/var/folders/8d/lqz6jwkd3d5b9pkp9tx006gc0000gp/T/d20160104-33457-1khh5tb/prong` does not exist.

Failed running dynamic analysis. Transpec runs your specs in a copied project directory. If your project requires some special setup or commands to run specs, use -c/--rspec-command option.
```

**Comment by yujinakayama** [comment]
It's caused the dependency outside of the `demo_app` project with relative path.

You should run the following:

```bash
$ cd bug_demo 
$ transpec demo_app/spec
```
