### ISSUE TITLE
transpec fails with undefined method 'this'

### ISSUE THREAD

**Issue by Skulli** [yujinakayama/transpec#114]
Getting the following error when starting transpec on my project on different machines:

    > transpec
    .rvm/rubies/ruby-2.1.7/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2157:in `method_missing': undefined method `this' for #<Gem::Specification:0x90257c transpec-3.1.1> (NoMethodError)
	from /.rvm/rubies/ruby-2.1.7/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1056:in `find_active_stub_by_path'
	from /.rvm/rubies/ruby-2.1.7/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:63:in `require'
	from /.rvm/gems/ruby-2.1.7@xxx/gems/transpec-3.1.1/bin/transpec:5:in `<top (required)>'
	from /.rvm/gems/ruby-2.1.7@xxx/bin/transpec:23:in `load'
	from /.rvm/gems/ruby-2.1.7@xxx/bin/transpec:23:in `<main>'
	from /.rvm/gems/ruby-2.1.7@xxx/bin/ruby_executable_hooks:15:in `eval'
	from /.rvm/gems/ruby-2.1.7@xxx/bin/ruby_executable_hooks:15:in `<main>'
    
    > ruby --version
    ruby 2.1.7p400 (2015-08-18 revision 51632) [x86_64-linux]
    > bundle exec rspec --version
    2.14.8
    > transpec --version (works only outside the project Folder)
    3.1.1
    > rvm --version
    rvm 1.26.11 (latest)

Same error when using rspec 2.99 and a setup on a Mac. 

After adding the gem to the Gemfile of the rails project, it is working.

**Comment by yujinakayama** [comment]
It seems to be an issue in rvm.

**Comment by testzugang** [comment]
Adding transpec to the Gemfile as a workaround solved the issue for me as well.

**Comment by yujinakayama** [comment]
Closing. Reopen if you still have the issue.

**Comment by dgilperez** [comment]
Thanks @testzugang. I'd suggest to update the README.

**Comment by pboling** [comment]
I have this issue as well.
- Installing latest rvm did not help.
- When I add transpec to the `.gemspec` of the gem I am working on I get this error:
```
∴ transpec
/Users/peterboling/.rvm/gems/ruby-2.3.0@foss/gems/parser-2.0.0/lib/parser/current.rb:32:in `<module:Parser>': Parser does not support parsing Ruby 2.3.0 (NotImplementedError)
       	from /Users/peterboling/.rvm/gems/ruby-2.3.0@foss/gems/parser-2.0.0/lib/parser/current.rb:1:in `<top (required)>'
       	from /Users/peterboling/.rvm/gems/ruby-2.3.0@foss/gems/transpec-0.0.10/lib/transpec/rewriter.rb:15:in `require'
       	from /Users/peterboling/.rvm/gems/ruby-2.3.0@foss/gems/transpec-0.0.10/lib/transpec/rewriter.rb:15:in `<top (required)>'
       	from /Users/peterboling/.rvm/gems/ruby-2.3.0@foss/gems/transpec-0.0.10/lib/transpec/cli.rb:5:in `require'
       	from /Users/peterboling/.rvm/gems/ruby-2.3.0@foss/gems/transpec-0.0.10/lib/transpec/cli.rb:5:in `<top (required)>'
       	from /Users/peterboling/.rvm/gems/ruby-2.3.0@foss/gems/transpec-0.0.10/bin/transpec:5:in `require'
       	from /Users/peterboling/.rvm/gems/ruby-2.3.0@foss/gems/transpec-0.0.10/bin/transpec:5:in `<top (required)>'
       	from /Users/peterboling/.rvm/gems/ruby-2.3.0@foss/bin/transpec:23:in `load'
       	from /Users/peterboling/.rvm/gems/ruby-2.3.0@foss/bin/transpec:23:in `<main>'
       	from /Users/peterboling/.rvm/gems/ruby-2.3.0@foss/bin/ruby_executable_hooks:15:in `eval'
       	from /Users/peterboling/.rvm/gems/ruby-2.3.0@foss/bin/ruby_executable_hooks:15:in `<main>'
```

Does this mean that transpec only works with Ruby < 2.3?

**Comment by Fivell** [comment]
+1 , have same issue
