### ISSUE TITLE
Weird error with ruby 2.3.0

### ISSUE THREAD

**Issue by shosti** [yujinakayama/transpec#115]
Unfortunately, the project I ran this on isn't open source so I can't give exact steps to reproduce. But for a particular spec in the middle of a pretty big suite, I'm getting the following (bizarre) error:

```
ruby: string.c:327: register_fstring: Assertion `(((struct RBasic*)(ret))->klass) == rb_cString' failed.

Failed running dynamic analysis. Transpec runs your specs in a copied project directory. If your project requires some special setup or commands to run specs, use -c/--rspec-command option.
```

`transpec --version`: 3.1.2
`ruby --version`: 3.2.0p0
`bundle exec rspec --version`: 3.1.7
Transpec was run without options (just `transpec`).

Relevant information: the spec works fine and passes when run by itself, and when run individually with `transpec -c`. We're also using `#frozen_string_literal: true` on all our files, although the result is the same when I delete that from the spec file.

Sorry I'm not able to give more specific information, just thought I'd report it in case anyone has seen something similar...

**Comment by yujinakayama** [comment]
I guess it's an issue in Ruby runtime so there's nothing Transpec can do with it.

* https://github.com/ruby/ruby/blob/v2_3_0/string.c#L327
