### ISSUE TITLE
Rails deprecation warnings

### ISSUE THREAD

**Issue by CBarraford** [yujinakayama/transpec#117]
Love this tool, saved me huge amounts of time, thanks! Is there any interest in support rails rspec convertions? The following is the issue that i'm plagued with. Will transpec support stuff like this?

```
DEPRECATION WARNING: ActionController::TestCase HTTP request methods will accept only
keyword arguments in future Rails versions.

Examples:

get :show, params: { id: 1 }, session: { user_id: 1 }
process :update, method: :post, params: { id: 1 }
```

**Comment by yujinakayama** [comment]
There's no plan for supporting conversion of Rails' API.
