### ISSUE TITLE
Handles Rspec 3.4.0?

### ISSUE THREAD

**Issue by simonzhu24** [yujinakayama/transpec#120]
Recently, I upgraded my Rspec to 3.4 and then got a number of errors:

Namely:
/Users/ximengzhu/.rvm/gems/ruby-2.3.0/gems/github_api-0.12.4/lib/github_api.rb:51:in `method_missing'

I wasn't sure how to fix this so I ran 'transpec' but wasn't sure if transpec supported Rspec 3.4?

**Comment by yujinakayama** [comment]
Please reopen after reporting the following information: https://github.com/yujinakayama/transpec/blob/master/CONTRIBUTING.md#reporting-an-issue
