### ISSUE TITLE
Ignore code already in new format.

### ISSUE THREAD

**Issue by leighhalliday** [yujinakayama/transpec#98]
I'm not sure if you feel this is necessary or not, but it is something I ran into while running the transpec code on our codebase, and you asked me to report which test was failing after the conversion. :)

We already had just a few places where we were already using the "expect(5).to eq(5)" format, which was converted again and came out with an extra expect().to wrapped around it.

From:
```ruby
expect(@campaign.supporters.size).to eq(1)
```

To:
```ruby
expect(expect(@campaign.supporters.size).to).to eq(1)
```

Thanks again for all your work on transpec!! It worked great!

**Comment by yujinakayama** [comment]
Thanks for the report. However I cannot reproduce the issue with the code.

```ruby
class Campaign
  def supporters
    [:foo]
  end
end

describe Campaign do
  before do
    @campaign = Campaign.new
  end

  it 'has a supporter' do
    expect(@campaign.supporters.size).to eq(1)
  end
end
```

```bash
$ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
$ bundle exec rspec --version
2.14.8
$ bundle exec rspec spec/test_spec.rb
.

Finished in 0.00119 seconds
1 example, 0 failures
```

Could you provide the environment details and the entire source of the spec file (if possible)?

**Comment by leighhalliday** [comment]
Ugh, I am sorry, this is totally my fault. It turns out I read it from the wrong branch, and the actual code that produced the double expect() code was because of some crazy code in our codebase... not sure how the tests passed!

This was the actual code:
```ruby
@campaign.supporters.size.should.should == 1
```

After seeing this code I guess it makes sense that it created the expect(expect().to).to code. It's a miracle the code even worked in the first place!

Please close this ticket. Again, thank you for your work on this code!! It helped us immensely.
