### ISSUE TITLE
Add specific flag for keeping mock/stub instead of double

### ISSUE THREAD

**Issue by jgeiger** [yujinakayama/transpec#99]
Mocha requires either stub or mock. I'd like the other deprecations to be done, but it would be nice to leave the Mocha specific code alone.

**Comment by yujinakayama** [comment]
Transpec automatically differentiate RSpec's `stub/mock` from Mocha's ones, and converts only RSpec's ones. So the suggested feature isn't needed.

**Comment by jgeiger** [comment]
Sadly this is not the case as today I've spend a good portion of my conversion changing the doubles back in to stubs/mocks to get my suite passing.

**Comment by yujinakayama** [comment]
Could you provide a reproducible example?

**Comment by yujinakayama** [comment]
Or probably you passed `-s/--skip-dynamic-analysis` option?

**Comment by jgeiger** [comment]
I've created a https://gist.github.com/jgeiger/f56f64da4287c5c17e98 of two files.

It might have to do with the dynamic analysis failing and the system just using static analysis.

**Comment by yujinakayama** [comment]
Please provide the full project setup including `spec_helper.rb` and `Gemfile`, etc.

Also it's strange you're using rspec-mocks' `any_instance` while using mocha.

**Comment by andyw8** [comment]
@yujinakayama Just FYI, `any_instance` is also a feature of mocha: https://github.com/freerange/mocha#quick-start
